// Location data service for countries and cities
export const locationData = {
  Morocco: {
    name: "Morocco",
    cities: [
      "Casablanca",
      "Rabat",
      "Marrakech",
      "Fes",
      "Tangier",
      "Agadir",
      "Meknes",
      "Oujda",
      "Kenitra",
      "Tetouan",
      "Safi",
      "El Jadida",
      "Nador",
      "Beni Mellal",
      "Taza",
      "Settat",
      "Berrechid",
      "Khouribga",
      "Larache",
      "Ksar El Kebir",
      "Khemisset",
      "Mohammedia",
      "Essaouira",
      "Taroudant",
      "Ouarzazate",
      "Dakhla",
      "Laayoune",
      "Ifrane",
      "Al Hoceima",
      "Chefchaouen",
    ],
  },
  France: {
    name: "France",
    cities: [
      "Paris",
      "Marseille",
      "Lyon",
      "Toulouse",
      "Nice",
      "Nantes",
      "Strasbourg",
      "Montpellier",
      "Bordeaux",
      "Lille",
      "Rennes",
      "Reims",
      "Saint-Étienne",
      "Le Havre",
      "Toulon",
      "Grenoble",
      "Dijon",
      "Angers",
      "Nîmes",
      "Villeurbanne",
    ],
  },
  Spain: {
    name: "Spain",
    cities: [
      "Madrid",
      "Barcelona",
      "Valencia",
      "Seville",
      "Zaragoza",
      "Málaga",
      "Murcia",
      "Palma",
      "Las Palmas",
      "Bilbao",
      "Alicante",
      "Córdoba",
      "Valladolid",
      "Vigo",
      "Gijón",
      "Hospitalet de Llobregat",
      "Granada",
      "Vitoria-Gasteiz",
      "A Coruña",
      "Elche",
    ],
  },
  "United States": {
    name: "United States",
    cities: [
      "New York",
      "Los Angeles",
      "Chicago",
      "Houston",
      "Phoenix",
      "Philadelphia",
      "San Antonio",
      "San Diego",
      "Dallas",
      "San Jose",
      "Austin",
      "Jacksonville",
      "Fort Worth",
      "Columbus",
      "Charlotte",
      "San Francisco",
      "Indianapolis",
      "Seattle",
      "Denver",
      "Boston",
    ],
  },
};

export const getCountries = () => {
  return Object.keys(locationData);
};

export const getCitiesByCountry = (country) => {
  return locationData[country]?.cities || [];
};

export const formatAddress = (country, city, street) => {
  return `${street}, ${city}, ${country}`;
};
